### ISSUE TITLE
bug(extension): GNOME 3.34 support

### ISSUE THREAD

**Issue by Striffly** [TimurKiyivinski/gnome-shell-night-light-slider-extension#50] opened 2019-10-07 14:45 UTC
**Describe the bug**
Extension does not work with GNOME Shell 3.34. 

**System Information:**
- OS: Arch Linux 5.3.4-arch1-1-ARCH
- GNOME Version: 3.34.0

**Comment by holic-cl** [comment] 2019-10-07 14:53
Same problem here, using Debian Sid

**Comment by kiyui** [comment] 2019-10-08 01:47
This is a duplicate of #48, 3.34 support has been released but I am unable to publish it. Again, sorry for that.

Release: https://github.com/kiyui/gnome-shell-night-light-slider-extension/releases/tag/12.0

Just copy the files over to `~/.local/share/gnome-shell/extensions` :smile:

**Closed as completed by kiyui** 2019-10-08 01:47 UTC
Labels: bug

**Comment by holic-cl** [comment] 2019-10-08 17:47
thanks, is working now
